### PR TITLE
Add convert cosmos address to other cosmos zones

### LINKED ISSUE #135: [Gemstone] Add bech32 address converter
Implement function to convert cosmos like address to another chain address with prefix

### Example

Input: `cosmos1h3laqcrmul79zwtw6j63ncsl0adfj07wgupylj`
HRP: `osmosis`

Output: `osmosis1h3laqcrmul79zwtw6j63ncsl0adfj07wm8vf00`

### PR DESCRIPTION
**Pull request by kehiy**
I think it should work, but something remained:

1. is the location of mod.rs ok?
2. should I add this to lib.rs on root of gemstone?

- Fixes #135

### CODE REVIEW

**Comment by 0xh3rman** [comment]
Thanks for the contribution, we will take care of the rest; we need to refactor `blockchain` crate a little bit and move all each chain's implementation to it

**Comment by kehiy** [comment]
@0xh3rman hi, please don't merge it. some changes are needed.

**Comment by kehiy** [comment]
@0xh3rman changes are done. sorry for wrong commit messages in last commit.

**Comment by kehiy** [comment]
@0xh3rman @gemcoder21 is everything OK now? can we merge?

**Review by 0xh3rman — APPROVED** [review]

**Pull request merged**
